---
title: react-rust-postgres  *red - container, green - network, blue - volume
---
graph LR
  subgraph network-client-side [network-client-side]
    frontend[frontend<br>port: 3000:3000]
    backend[backend<br>depends on: db]
  end
  subgraph network-frontend [network-frontend<br>name: custom_frontend<br>driver: custom-driver-1]
  end
  subgraph network-server-side [network-server-side]
    backend[backend<br>depends on: db]
    db[db<br>image: postgres:12-alpine<br>port: 5432:5432]
  end
  volume-backend-cache[volume-backend-cache<br>]
  class volume-backend-cache volume
  volume-db-data[volume-db-data<br>]
  class volume-db-data volume
  backend -- "dependency" --> db
  backend -- "volume" --> volume-backend-cache
  db -- "volume" --> volume-db-data
classDef container fill:#f00,color:#fff;
classDef network fill:#0f0,color:#fff;
classDef volume fill:#00f,color:#fff;