# This is a file to test --config option,
# come from `examples/awesome-compose/angular/`
services:
  web:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules
